name: borc_defteri
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+13

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.1.0
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0
  google_mobile_ads: ^5.0.0
  url_launcher: ^6.2.6
  intl: ^0.19.0
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # === BU HİSSƏNİ DÜZƏLTDİM ===
  assets:
    - assets/google_logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"